version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./../environment/mysql:/etc/mysql/conf.d

volumes:
  mysql_db_data:
